apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: klage-permittering-refusjon
  namespace: teamloennskomp
  labels:
    team: teamloennskomp
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ingress}}
  liveness:
    path: /klage-permittering-refusjon/internal/isAlive
    initialDelay: 20
  readiness:
    path: /klage-permittering-refusjon/internal/isReady
    initialDelay: 20
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
    clientUri: {{ingress}}
    postLogoutRedirectURIs:
      - {{ingress}}/logout-callback
  accessPolicy:
    outbound:
      rules:
        - application: klage-permittering-refusjon-api
          cluster: {{api-cluster}}
          namespace: teamloennskomp
      external:
        - host: {{decorator-external-host}}
        - host: {{api-external-host}}
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: {{loginservice-login-url}}
    - name: LOGINSERVICE_LOGOUT_URL
      value: {{loginservice-logout-url}}
    - name: BACKEND_BASEURL
      value: {{api-external-host}}
    - name: API_AUDIENCE
      value: {{api-audience}}
    - name: AMPLITUDE_API_KEY_DEV
      valueFrom:
        secretKeyRef:
          name: amplitude-api-key
          key: dev
    - name: AMPLITUDE_API_KEY_PROD
      valueFrom:
        secretKeyRef:
          name: amplitude-api-key
          key: prod
