name: Bygg og deploy master

on:
  push:
    branches:
      - 'master'

env:
  IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  bygg:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Logg inn i GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Bygg, tag og push Docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-gcp.json
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/prod-gcp.json
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}
